quarkus:
  application:
    name: coffee_Metrics

  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${postgres.url}/${postgres.schema}
    username: ${postgres.username}
    password: ${postgres.password}
    # Equivalente ao HikariCP
    max-size: 20
    min-size: 10
    acquire-timeout: 250ms
    idle-removal-interval: 10M
    name: master
    # Desabilita o auto-commit
    auto-commit: false

  hibernate-orm:
    log:
      sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect
    database:
      generation: none
    # Equivalente ao `hibernate.globally_quoted_identifiers`
    physical-naming-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Outros possíveis ajustes
    # statistics: false

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-description: init
    baseline-version: 0
    locations: classpath:db/migration
    user: ${postgres.username}
    password: ${postgres.password}
    url: jdbc:postgresql://${postgres.url}/${postgres.schema}

postgres:
  url: localhost:5432
  username: postgres
  password: postgres
  schema: coffee_app