version: '3.7'
services:
  postgres:
    container_name: coffee_metrics_postgres
    image: postgres:15
    restart: always
    tty: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coffee_app
      PGDATA: /data/postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - coffee_metrics_network
networks:
  coffee_metrics_network:
    driver: bridge