CREATE TABLE "tb_coffee" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "name" VARCHAR(255) NOT NULL,
  "points" INTEGER,
  "name_producer" VARCHAR(255),
  "region" VARCHAR(255),
  "altitude" INTEGER,
  "roasting_date" TIMESTAMP(6) WITH TIME ZONE,
  "roasting_level" VARCHAR(255) NOT NULL CHECK ("roasting_level" IN ('LIGHT', 'MEDIUM', 'DARK')),
  "sensory" VARCHAR(255) NOT NULL,
  "size_type" VARCHAR(255),
  "species" VARCHAR(255),
  "roasting_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_coffee_roasting" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "name" VARCHAR(255) NOT NULL,
  "region" VARCHAR(255),
  PRIMARY KEY ("id")
);

ALTER TABLE IF EXISTS "tb_coffee"
ADD CONSTRAINT fk_coffee_roasting FOREIGN key ("roasting_id") REFERENCES "tb_coffee_roasting";