CREATE TABLE "tb_grinding" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "brand" VARCHAR(255) NOT NULL,
  "clicks" INTEGER,
  "model" VARCHAR(255),
  "interval_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_grinding_config" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "clicks" INTEGER,
  "grinding_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_grinding_config_interval" (
  "grinding_config_id" BIGINT NOT NULL,
  "click_initial" INTEGER,
  "click_final" INTEGER,
  "category_name" VARCHAR(255) NOT NULL,
  PRIMARY KEY ("grinding_config_id", "category_name")
);

ALTER TABLE IF EXISTS "tb_grinding"
DROP CONSTRAINT if EXISTS "UKmji5qhmv4valwq0xtcfku01dv";

ALTER TABLE IF EXISTS "tb_grinding"
ADD CONSTRAINT "UKmji5qhmv4valwq0xtcfku01dv" UNIQUE ("interval_id");

ALTER TABLE IF EXISTS "tb_grinding_config"
DROP CONSTRAINT if EXISTS "UK8t0uro9sh4m1xn8gau7hkwg3e";

ALTER TABLE IF EXISTS "tb_grinding_config"
ADD CONSTRAINT "UK8t0uro9sh4m1xn8gau7hkwg3e" UNIQUE ("grinding_id");

ALTER TABLE IF EXISTS "tb_grinding"
ADD CONSTRAINT "FKil29moqb42jh3lwtp2r2opl5o" FOREIGN key ("interval_id") REFERENCES "tb_grinding_config";

ALTER TABLE IF EXISTS "tb_grinding_config"
ADD CONSTRAINT fk_config_grinding FOREIGN key ("grinding_id") REFERENCES "tb_grinding";

ALTER TABLE IF EXISTS "tb_grinding_config_interval"
ADD CONSTRAINT "FKfpv8uqgrhugiel1kdia6y168e" FOREIGN key ("grinding_config_id") REFERENCES "tb_grinding_config";