CREATE TABLE "tb_creator" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "name" VARCHAR(255) NOT NULL,
  "nick_name" VARCHAR(255),
  "phone" VARCHAR(255),
  "country" VARCHAR(255),
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_users" (
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "email" VARCHAR(255) NOT NULL,
  "password" VARCHAR(255),
  "status" VARCHAR(255),
  "creator_id" BIGINT NOT NULL,
  PRIMARY KEY ("creator_id")
);

CREATE TABLE "tb_creator_favorites" (
  "creator_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "grinding_id" BIGINT,
  PRIMARY KEY ("creator_id")
);

CREATE TABLE "tb_creator_posts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "description" VARCHAR(255) NOT NULL,
  "file_url" VARCHAR(255),
  "title" VARCHAR(255) NOT NULL,
  "creator_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "comment" VARCHAR(255) NOT NULL,
  "comment_bind_id" BIGINT,
  "creator_id" BIGINT,
  "post_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_units_system" (
  "favorite_id" BIGINT NOT NULL,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "measures" VARCHAR(255),
  "proportion" VARCHAR(255),
  "temperature" VARCHAR(255),
  "weight" VARCHAR(255),
  PRIMARY KEY ("favorite_id")
);

ALTER TABLE IF EXISTS "tb_comments"
ADD CONSTRAINT fk_comments_comment_bind FOREIGN key ("comment_bind_id") REFERENCES "tb_comments";

ALTER TABLE IF EXISTS "tb_comments"
ADD CONSTRAINT fk_comments_creator FOREIGN key ("creator_id") REFERENCES "tb_creator";

ALTER TABLE IF EXISTS "tb_comments"
ADD CONSTRAINT fk_comments_post FOREIGN key ("post_id") REFERENCES "tb_creator_posts";

ALTER TABLE IF EXISTS "tb_creator_favorites"
ADD CONSTRAINT fk_favorites_grinding FOREIGN key ("grinding_id") REFERENCES "tb_grinding";

ALTER TABLE IF EXISTS "tb_creator_favorites"
ADD CONSTRAINT fk_favorites_creator FOREIGN key ("creator_id") REFERENCES "tb_creator";

ALTER TABLE IF EXISTS "tb_creator_posts"
ADD CONSTRAINT fk_post_creator FOREIGN key ("creator_id") REFERENCES "tb_creator";

ALTER TABLE IF EXISTS "tb_units_system"
ADD CONSTRAINT fk_units_system_favorites FOREIGN key ("favorite_id") REFERENCES "tb_creator_favorites";

ALTER TABLE IF EXISTS "tb_users"
ADD CONSTRAINT fk_users_creator FOREIGN key ("creator_id") REFERENCES "tb_creator";