CREATE TABLE "tb_category" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "description" VARCHAR(255) NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_subcategory" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "description" VARCHAR(255) NOT NULL,
  "category_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_tag" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "description" VARCHAR(255) NOT NULL,
  "subcategory_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_recipes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "description" VARCHAR(255) NOT NULL,
  "extraction_time" INTEGER NOT NULL,
  "grams_of_coffee" INTEGER NOT NULL,
  "grams_of_water" INTEGER NOT NULL,
  "grinding" VARCHAR(255) NOT NULL,
  "proportion" VARCHAR(255) NOT NULL,
  "post_id" BIGINT,
  "subcategory_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_recipe_steps" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "description" VARCHAR(255) NOT NULL,
  "duration_time" INTEGER,
  "execution_order" INTEGER NOT NULL,
  "recipe_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_recipes_equipment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "equipment" VARCHAR(255) NOT NULL,
  "mandatory" BOOLEAN NOT NULL,
  "recipe_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_creator_favorites_recipes" (
  "recipe_id" BIGINT NOT NULL,
  "creator_favorite_id" BIGINT NOT NULL,
  PRIMARY KEY ("recipe_id", "creator_favorite_id")
);

CREATE TABLE "tb_notes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "created_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "updated_at" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
  "version" BIGINT,
  "description" VARCHAR(255) NOT NULL,
  "creator_id" BIGINT,
  "recipe_id" BIGINT,
  PRIMARY KEY ("id")
);

CREATE TABLE "tb_notes_coffees" (
  "notes_id" BIGINT NOT NULL,
  "coffee_id" BIGINT NOT NULL
);

CREATE TABLE "tb_notes_grindings" (
  "notes_id" BIGINT NOT NULL,
  "grinding_id" BIGINT NOT NULL
);

CREATE INDEX idx_subcategory_id ON "tb_recipes" ("subcategory_id");

ALTER TABLE IF EXISTS "tb_subcategory"
ADD CONSTRAINT fk_subcategory_category FOREIGN key ("category_id") REFERENCES "tb_category";

ALTER TABLE IF EXISTS "tb_tag"
ADD CONSTRAINT fk_tag_subcategory FOREIGN key ("subcategory_id") REFERENCES "tb_subcategory";

ALTER TABLE IF EXISTS "tb_recipes"
ADD CONSTRAINT fk_recipe_post FOREIGN key ("post_id") REFERENCES "tb_creator_posts";

ALTER TABLE IF EXISTS "tb_recipes"
ADD CONSTRAINT fk_recipe_subcategory FOREIGN key ("subcategory_id") REFERENCES "tb_subcategory";

ALTER TABLE IF EXISTS "tb_recipes_equipment"
ADD CONSTRAINT fk_equipment_recipe FOREIGN key ("recipe_id") REFERENCES "tb_recipes";

ALTER TABLE IF EXISTS "tb_recipe_steps"
ADD CONSTRAINT fk_steps_recipe FOREIGN key ("recipe_id") REFERENCES "tb_recipes";

ALTER TABLE IF EXISTS "tb_creator_favorites_recipes"
ADD CONSTRAINT fk_favorites_recipes_favorite_id FOREIGN key ("creator_favorite_id") REFERENCES "tb_recipes";

ALTER TABLE IF EXISTS "tb_creator_favorites_recipes"
ADD CONSTRAINT fk_favorites_recipes_recipe_id FOREIGN key ("recipe_id") REFERENCES "tb_creator_favorites";

ALTER TABLE IF EXISTS "tb_notes"
DROP CONSTRAINT if EXISTS "UKovosuxr103np5kj5brod8jvtw";

ALTER TABLE IF EXISTS "tb_notes"
ADD CONSTRAINT "UKovosuxr103np5kj5brod8jvtw" UNIQUE ("recipe_id");

ALTER TABLE IF EXISTS "tb_notes"
ADD CONSTRAINT fk_notes_creator FOREIGN key ("creator_id") REFERENCES "tb_creator";

ALTER TABLE IF EXISTS "tb_notes"
ADD CONSTRAINT fk_notes_recipe FOREIGN key ("recipe_id") REFERENCES "tb_recipes";

ALTER TABLE IF EXISTS "tb_notes_coffees"
ADD CONSTRAINT fk_notes_coffees_coffee_id FOREIGN key ("coffee_id") REFERENCES "tb_coffee";

ALTER TABLE IF EXISTS "tb_notes_coffees"
ADD CONSTRAINT fk_notes_coffees_notes_id FOREIGN key ("notes_id") REFERENCES "tb_notes";

ALTER TABLE IF EXISTS "tb_notes_grindings"
ADD CONSTRAINT fk_notes_grindings_grinding_id FOREIGN key ("grinding_id") REFERENCES "tb_grinding";

ALTER TABLE IF EXISTS "tb_notes_grindings"
ADD CONSTRAINT fk_notes_grindings_notes_id FOREIGN key ("notes_id") REFERENCES "tb_notes";